#!/bin/bash

for file in `tree -if --noreport | egrep "\.(patch|patch1|diff)$"`; do
    echo Apply $file > /dev/null
    patch -p1 < $file
    if [ $? != 0 ]; then
        echo "Failed"
        exit 1
    fi
done
echo "Done"
