#
# Common code for all Loongson based systems
#

obj-$(CONFIG_MACH_LOONGSON) += common/

#
# Lemote Fuloong mini-PC (Loongson 2E-based)
#

obj-$(CONFIG_LEMOTE_FULOONG2E)	+= fuloong-2e/

#
# Lemote loongson2f family machines
#

obj-$(CONFIG_LEMOTE_MACH2F)  += lemote-2f/

#
# Dexxon gdium netbook, based on loongson 2F and SM502
#

obj-$(CONFIG_DEXXON_GDIUM)  += gdium/
